CREATE TABLE DRUG (ID NUMBER(5) NOT NULL, NAME VARCHAR2(20), PRICE DECIMAL(5,2));
ALTER TABLE DRUG ADD PRIMARY KEY (ID);
CREATE TABLE DRUG_DISEASE(DRUG_ID NUMBER(5) NOT NULL ,DISEASE_ID NUMBER(5));
ALTER TABLE DRUG_DISEASE ADD PRIMARY KEY (DRUG_ID);